#!/bin/bash
clear
echo ""
echo "Welcome to XtreamPlus installer"
echo "Please wait installer is preparing"
sudo apt-get update 2>&1 >/dev/null
echo "Installing missing components..."
apt-get install libxslt1-dev -y 2>&1 >/dev/null
echo "Downloading latest installer..."
apt-get install libcurl3 libgeoip-dev -y 2>&1 >/dev/null
echo "Starting..."
apt-get install python git -y 2>&1 >/dev/null
wget -q https://raw.githubusercontent.com/kadirgecit/testing/main/latest.py 
sudo python latest.py
wget -q https://raw.githubusercontent.com/kadirgecit/testing/main/glances.sh
sudo sh glances.sh 2>&1 >/dev/null
sudo rm glances.sh
echo "Cleaning..."
sudo rm latest.py













