#!/bin/sh
### Copyright 2021. XtreamPlus Team. All rights reserved.
clear
echo ""
echo "XtreamPlus Command Line Installer"
echo "Preparing..."
echo "Installing Components..."
sudo apt-get update > /dev/null
apt-get install libxslt1-dev libcurl3 libgeoip-dev python git -y > /dev/null
wget -q https://raw.githubusercontent.com/kadirgecit/testing/main/install_new.py 
sudo python install.py
sudo rm install.py
